services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: motortown-server
    environment:
      STEAM_USERNAME: $STEAM_USERNAME
      STEAM_PASSWORD: $STEAM_PASSWORD
    volumes:
      - ./DedicatedServerConfig.json:/app/DedicatedServerConfig.json
    ports:
      - 7777:7777
      - 27015:27015
    restart: unless-stopped